services:
  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # MySQL service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_DATABASE: capstone_db
    ports:
      - "3306:3306"

volumes:
  mysql-data: